@baseUrl=http://localhost:3000/api

@resourceName=products

#Products

# @name getAll
GET {{baseUrl}}/{{resourceName}}

###

# @name filterProducts

GET {{baseUrl}}/{{resourceName}}?price_gte=100
###

# @name filterLikeProducts

GET {{baseUrl}}/{{resourceName}}?color_like=indig

###
# @name pagination

GET {{baseUrl}}/{{resourceName}}?_page=1&_limit=5

###
# @name sort
GET {{baseUrl}}/{{resourceName}}?_sort=price&_order=asc

###
# @name addNews

POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json

{
    "categoryId": "e8e7db89-1e17-4b11-a5ae-866daf42e716",
    "name": "Small Cotton Shirt",
    "color": "silver",
    "price": 456,
    "description": "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
    "thumbnailUrl": "http://placeimg.com/400/400"
  }

###

# @name update
PATCH  {{baseUrl}}/{{resourceName}}/6bGtanS
Content-Type: application/json

{
  "name": "Bui Minh Son"
}

###

# @name remove

DELETE {{baseUrl}}/{{resourceName}}/ZHkNgEk